### ISSUE TITLE
pipenv doesn't allow .envrc files to be sourced

### ISSUE THREAD

**Issue by thepreacher** [fisherman/pipenv#11]
For my flask apps, I've recently started using `direnv` to load project specific environment settings via `.envrc` files. I use the fish shell and have as such installed the pipenv plugin for integration with pipenv. However, when I cd into a pipenv created virtualenv containing a `.envrc`, the fish pipenv plugin rightly activates the virtualenv environment but the `.envrc` file is not sourced. 

Therefore if I give the command `flask run` for example, I get the warning 
```
Usage: flask run [OPTIONS]
Error: Could not locate Flask application. You did not provide the FLASK_APP environment variable.
```
I therefore have to `Ctrl+D` to exit the virtualenv, which then causes `direnv` to source the `.envrc`, after which I give the `pipenv shell` command to activate the virtualenv again.

To save me from doing this every time, I've uninstalled the pipenv plugin for the moment.

**Comment by kennethreitz** [comment]
I don't have any trouble using direnv and pipenv together.
