### ISSUE TITLE
Pipenv called for any directory when i cd into it.

### ISSUE THREAD

**Issue by tshirtman** [fisherman/pipenv#2]
I just installed fisher and pipenv (used fish without a plugin manager before), and when i open a shell and cd to any directory, it auto creates a virtualenv/Pipfile and load the subshell. It's only once per new shell, but it's not really an expected or desirable behavior

    gabriel@gryphon:~> mkdir plop
    gabriel@gryphon:~> cd plop
    Creating a Pipfile for this project...
    Creating a virtualenv for this project...
    ⠋No virtualenv has been created for this project yet!
    Running virtualenv with interpreter /usr/bin/python2
    New python executable in /home/gabriel/.local/share/virtualenvs/plop-Fqtl0Bn_/bin/python2
    Also creating executable in /home/gabriel/.local/share/virtualenvs/plop-Fqtl0Bn_/bin/python
    Installing setuptools, pkg_resources, pip, wheel...done.

    Virtualenv location: /home/gabriel/.local/share/virtualenvs/plop-Fqtl0Bn_
    Launching subshell in virtual environment. Type 'exit' or 'Ctrl+D' to return.

Thanks for all the fish!

edit: i had virtualfish and auto_activation.fish, installed (without fisherman) i commented/moved them and i still get the behavior.

**Comment by brizzbane** [comment]
came here to see if this was an issue for others, looks like it is.  (new to fish, and this plugin)

I thought the plugin was supposed to activate a virtualenv if you happened to cd into a directory that had a virtualenv.  To me, this seems like the plugin assumes that you will always be working with a virtualenv...

**Comment by jmcs** [comment]
`sh -c 'pipenv --venv &> /dev/null'` always exits with status code 0
