### ISSUE TITLE
auto-deactivate, like pyenv-virtualenv

### ISSUE THREAD

**Issue by toejough** [fisherman/pipenv#5]
If I have pyenv-virtualenv hooks installed, then when I cd into a (sub)directory of a project, the virtualenv is automatically loaded.  When I cd out of that project, the virtualenv is unloaded.

This plugin enables the activation behavior, but not yet the deactivation.  Could the deactivation behavior be added?

**Comment by kennethreitz** [comment]
pull requests accepted!

**Comment by toejough** [comment]
👏
