### ISSUE TITLE
Plugin makes shell startup much slower

### ISSUE THREAD

**Issue by skorokithakis** [fisherman/pipenv#9]
This plugin makes my shell's startup time much slower, from "imperceptible" to "~1 sec". Is there any way it could be loaded lazily?

**Comment by ovidner** [comment]
I have the same problem, and solved it by inlining the completion expression. Feel free to try it (`fisher install ovidner/pipenv`) and let me know if works (or more importantly, if it doesn't) :)

**Comment by skorokithakis** [comment]
I can confirm that this leaves my shell's startup time unaffected.

**Comment by kennethreitz** [comment]
@ovidner can you send a PR?
